<a href="https://colab.research.google.com/github/harshithachanta/purchasecasestudy/blob/main/purchasecasestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Purchase case study**

Dataset: https://drive.google.com/file/d/1oSP_vX0x8AiSb0TLACVvkePh0WM-6R1S/view?usp=sharing

# 🧩 Case Study: Understanding Consumer Purchasing Behavior in an E-Commerce Festival Sale
📌 **Problem Statement**

An e-commerce company has conducted a large-scale festival sale and collected detailed transaction-level data from over 550,000 purchase records. The business wants to understand what drives customer purchases, identify key customer segments, and uncover which product categories perform best across different demographics.

Your task in this case study is to analyze this dataset to answer the following core business question:

“What customer and product characteristics most strongly influence purchase amounts during the festival sale?”

By exploring patterns across gender, age groups, occupations, city categories, and product preferences, the goal is to help the company improve future marketing strategies, personalize recommendations, and optimize inventory planning.

📊** Dataset Explanation**

The dataset contains 550,068 rows and 12 columns, where each row represents a single transaction made by a user during the sale. Below is a clear explanation of each feature:

**Column	Description**

**User_ID**	Unique ID assigned to each customer (integer). Helps track multiple purchases by the same user.

**Product_ID**	Unique ID for each product purchased.

**Gender**	Customer gender (‘M’ or ‘F’). Useful for gender-based segmentation.

**Age**	Age group of the customer (e.g., ‘18–25’, ‘26–35’, etc.).

**Occupation**	Encoded integer representing customer’s occupation category.

**City_Category**	City tier where the customer resides (‘A’, ‘B’, or ‘C’).

Stay_In_Current_City_Years	How long the customer has lived in the current city (e.g., ‘1’, ‘2’, ‘4+’).

**Marital_Status**	Customer marital status (0 = Single, 1 = Married).

**Product_Category_1**	Main product category purchased (integer-coded).

**Product_Category_2**	Secondary product category (nullable — many products don’t have one).

**Product_Category_3**	Tertiary product category (also nullable).

**Purchase**	Purchase amount spent by the customer in that transaction. This is the key target variable for analysis.

# 📝 Why This Dataset Is Interesting

It combines customer demographics, product metadata, and financial data.

It has meaningful business insights potential (segmentation, demand forecasting, purchase behavior modeling).

It is realistic—missing values, categorical variables, and large size replicate actual industry datasets.

Perfect for EDA, visualization, feature engineering, and machine learning tasks.

🎯 **Possible Analytical Goals**

This dataset can be used to:

Analyze which demographic groups spend the most.

Understand how product categories influence purchase amounts.

Explore differences between city tiers and customer retention.

Build predictive models (e.g., regressions, tree-based models) to estimate purchase amounts.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df1 = pd.read_csv('train.csv')
df1.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [2]:
df1.shape

(550068, 12)

In [3]:
df1['Stay_In_Current_City_Years'].value_counts()

Stay_In_Current_City_Years
1     193821
2     101838
3      95285
4+     84726
0      74398
Name: count, dtype: int64

In [4]:
df1['Stay_In_Current_City_Years']=df1['Stay_In_Current_City_Years'].replace('4+','4')

In [5]:
df1['Stay_In_Current_City_Years'].value_counts()

Stay_In_Current_City_Years
1    193821
2    101838
3     95285
4     84726
0     74398
Name: count, dtype: int64

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [7]:
df1['Stay_In_Current_City_Years']=df1['Stay_In_Current_City_Years'].astype(int)
# df1['Stay_In_Current_City_Years']=df1['Stay_In_Current_City_Years'].astype(int,inplace=True)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  int64
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(6), object(4)
memory usage: 50.4+ MB

In [9]:
df1['Age'].value_counts()

Age
26-35    219587
36-45    110013
18-25     99660
46-50     45701
51-55     38501
55+       21504
0-17      15102
Name: count, dtype: int64

In [10]:
df1['Age']=df1['Age'].replace('55+','55-100')

In [11]:
df1['Age'].value_counts()

Age
26-35     219587
36-45     110013
18-25      99660
46-50      45701
51-55      38501
55-100     21504
0-17       15102
Name: count, dtype: int64

In [12]:
df1.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [13]:
df1['Product_Category_2'].fillna(0,inplace=True)
df1['Product_Category_3'].fillna(0,inplace=True)

/tmp/ipykernel_1515/2106239061.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Product_Category_2'].fillna(0,inplace=True)
/tmp/ipykernel_1515/2106239061.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Product_Category_3'].fillna(0,inplace=True)

In [14]:
df1.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [15]:
df1.describe().round(2)

,User_ID,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,550068.00,550068.00,550068.00,550068.00,550068.00,550068.00,550068.00,550068.00
mean,1003028.84,8.08,1.86,0.41,5.40,6.74,3.84,9263.97
std,1727.59,6.52,1.29,0.49,3.94,6.22,6.25,5023.07
min,1000001.00,0.00,0.00,0.00,1.00,0.00,0.00,12.00
25%,1001516.00,2.00,1.00,0.00,1.00,0.00,0.00,5823.00
50%,1003077.00,7.00,2.00,0.00,5.00,5.00,0.00,8047.00
75%,1004478.00,14.00,3.00,1.00,8.00,14.00,8.00,12054.00
max,1006040.00,20.00,4.00,1.00,20.00,18.00,18.00,23961.00

In [16]:
df1.describe(include='object')

       Product_ID  Gender     Age City_Category
count      550068  550068  550068        550068
unique       3631       2       7             3
top     P00265242       M   26-35             B
freq         1880  414259  219587        231173

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
df1['City_Category']=le.fit_transform(df1['City_Category'])

In [22]:
df1['Gender']=le.fit_transform(df1['Gender'])
df1['Age']=le.fit_transform(df1['Age'])
df1['Product_ID']=le.fit_transform(df1['Product_ID'])

In [24]:
df1.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,672,0,0,10,0,2,0,3,0.0,0.0,8370
1,1000001,2376,0,0,10,0,2,0,1,6.0,14.0,15200
2,1000001,852,0,0,10,0,2,0,12,0.0,0.0,1422
3,1000001,828,0,0,10,0,2,0,12,14.0,0.0,1057
4,1000002,2734,1,6,16,2,4,0,8,0.0,0.0,7969

#**Statistics**
Q1) it was observed that the average purchase made by the men of the age 18-25 was 10000.Is it still same?

In [33]:
df1['Age'].value_counts()

Age
2    219587
3    110013
1     99660
4     45701
5     38501
6     21504
0     15102
Name: count, dtype: int64

In [30]:
data=df1[(df1['Age']==1) & (df1['Gender']==1)]

In [31]:
data.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
97,1000021,2094,1,1,16,1,0,0,3,12.0,0.0,3055
98,1000022,3370,1,1,15,0,4,0,1,8.0,17.0,12099
99,1000022,2024,1,1,15,0,4,0,5,8.0,0.0,8797
100,1000022,1855,1,1,15,0,4,0,3,4.0,0.0,10681
101,1000022,1065,1,1,15,0,4,0,8,14.0,0.0,7801

In [32]:
data['Purchase'].mean()

np.float64(9440.94297099904)

In [36]:
sample=data.sample(3600,random_state=1)
sample.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1720,1000273,920,1,1,4,1,2,1,5,0.0,0.0,8793
220913,1004041,970,1,1,3,1,2,0,5,0.0,0.0,8898
517159,1001647,3300,1,1,18,1,0,0,18,0.0,0.0,3091
53833,1002186,1197,1,1,5,2,4,0,1,11.0,0.0,8308
403307,1002010,2035,1,1,4,1,0,0,5,0.0,0.0,5445

#null hypothesis=mean will be equal to 10k
#alternative=mean will not be equal to 10k

In [38]:
#one sample t-test
from scipy.stats import ttest_1samp

In [39]:
pop_mean=10000

In [42]:
t_stat,p_value=ttest_1samp(sample['Purchase'],pop_mean)
print(t_stat,p_value)
if p_value<0.05:
  print('we reject the null hypothesis')
else:
  print('we accept the null hypothesis')

-6.431071711880019 1.433735055967615e-10
we reject the null hypothesis

#**Q2 is the average purchase made by men and women of the age 18-25 same?**

In [43]:
data_men_sample=df1[(df1['Gender']==1) & (df1['Age']==1)]
data_women_sample=df1[(df1['Gender']==0) & (df1['Age']==1)]

In [44]:
data_men_sample.shape

(75032, 12)

In [45]:
data_women_sample.shape

(24628, 12)

In [46]:
data_men_sample['Purchase'].mean()

np.float64(9440.94297099904)

In [47]:
data_women_sample['Purchase'].mean()

np.float64(8343.180201396784)

In [49]:
from scipy.stats import f

In [53]:
F=data_men_sample.Purchase.mean()/data_women_sample.Purchase.mean()
F

np.float64(1.1315760589011936)

In [52]:
dff1=len(data_men_sample)-1
dff2=len(data_women_sample)-1
print(dff1,dff2)

75031 24627

In [56]:
import scipy
p_val=1-scipy.stats.f.cdf(F, dff1, dff2)
print(p_val)
if p_val<0.05:
  print('we reject the null hypothesis')
else:
  print('we accept the null hypothesis')

1.1102230246251565e-16
we reject the null hypothesis